import type { Vec3 } from '@/types/blueprint'

export type LightCategory =
  | 'ambient'
  | 'key'
  | 'fill'
  | 'accent'
  | 'task'
  | 'decorative'

export type EngineLightType =
  | 'point'
  | 'spot'
  | 'area'
  | 'sun'
  | 'led_strip'

export interface LightPreset {
  type: EngineLightType
  category: LightCategory
  intensity: number
  color: string
  temperature: number
  castShadow: boolean
  angle?: number
  decay?: number
  areaWidth?: number
  areaHeight?: number
  spotBlend?: number
}

export interface LightPlacement {
  lightId: string
  type: EngineLightType
  category: LightCategory
  position: Vec3
  rotation: Vec3
  target: Vec3 | null
  color: string
  temperature: number
  intensity: number
  castShadow: boolean
  angle: number
  decay: number
  areaWidth: number
  areaHeight: number
  spotBlend: number
  visible: boolean
  metadata: Record<string, unknown>
}

export interface LightingEngineResult {
  placements: LightPlacement[]
  nodesAdded: number
  errors: string[]
  warnings: string[]
  stats: {
    totalLights: number
    byType: Record<string, number>
    byCategory: Record<string, number>
    blueprintLights: number
    autoGenerated: number
  }
}
