import type { BoothBlueprint } from '@/types/blueprint'
import type { Scene, SceneNode } from '@/types/scene-graph'
import type { LightPlacement, LightingEngineResult } from './lighting-types'
import { resolveBlueprintLight, generateAutoLights } from './light-resolver'
import { validateLightPlacements } from './lighting-validator'

function generateId(prefix: string): string {
  return `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`
}

function mapToSceneLightType(type: string): string {
  switch (type) {
    case 'spot': return 'spotlight'
    case 'area': return 'area'
    case 'sun': return 'directional'
    case 'point': return 'point'
    case 'led_strip': return 'led_strip'
    default: return type
  }
}

function createLightNode(placement: LightPlacement, parentGroupId: string): SceneNode {
  return {
    id: generateId('light'),
    name: `${placement.category}_${placement.type}_${placement.lightId}`,
    type: 'light',
    parentId: parentGroupId,
    transform: {
      position: placement.position,
      rotation: placement.rotation,
      scale: { x: 1, y: 1, z: 1 },
    },
    mesh: null,
    material: null,
    camera: null,
    light: {
      lightType: mapToSceneLightType(placement.type),
      color: placement.color,
      intensity: placement.intensity,
      castShadow: placement.castShadow,
      angle: placement.angle > 0 ? placement.angle : undefined,
      decay: placement.decay > 0 ? placement.decay : undefined,
      target: placement.target ?? undefined,
    },
    visible: placement.visible,
    tags: ['light', placement.type, placement.category],
    metadata: {
      lightId: placement.lightId,
      category: placement.category,
      temperature: placement.temperature,
      areaWidth: placement.areaWidth,
      areaHeight: placement.areaHeight,
      spotBlend: placement.spotBlend,
      ...placement.metadata,
    },
  }
}

export function runLightingEngine(
  blueprint: BoothBlueprint,
  scene: Scene
): { scene: Scene; result: LightingEngineResult } {
  const nodes = [...scene.nodes]

  const existingLightingNodes = nodes.filter(
    n => n.type === 'light' && n.metadata.lightId && n.tags.includes('light')
  )
  const existingLightIds = new Set(
    existingLightingNodes.map(n => n.metadata.lightId as string).filter(Boolean)
  )

  const blueprintPlacements: LightPlacement[] = (blueprint.lights ?? []).map(
    (light, i) => resolveBlueprintLight(light, i)
  )

  const autoPlacements = generateAutoLights(
    blueprint.booth.dimensions,
    blueprintPlacements
  )

  const allPlacements = [...blueprintPlacements, ...autoPlacements]
  const validation = validateLightPlacements(allPlacements)

  let lightingGroupId = nodes.find(
    n => n.type === 'group' && n.name === 'Lighting'
  )?.id

  if (!lightingGroupId) {
    const rootId = nodes.find(n => n.type === 'root')?.id
    if (!rootId) {
      return {
        scene,
        result: {
          placements: [],
          nodesAdded: 0,
          errors: ['No root node found'],
          warnings: [],
          stats: { totalLights: 0, byType: {}, byCategory: {}, blueprintLights: 0, autoGenerated: 0 },
        },
      }
    }

    lightingGroupId = generateId('grp_lighting')
    nodes.push({
      id: lightingGroupId,
      name: 'Lighting',
      type: 'group',
      parentId: rootId,
      transform: { position: { x: 0, y: 0, z: 0 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1, y: 1, z: 1 } },
      mesh: null,
      material: null,
      camera: null,
      light: null,
      visible: true,
      tags: ['lighting'],
      metadata: {},
    })
  }

  let nodesAdded = 0
  for (const placement of allPlacements) {
    if (existingLightIds.has(placement.lightId)) continue
    nodes.push(createLightNode(placement, lightingGroupId))
    nodesAdded++
  }

  const byType: Record<string, number> = {}
  const byCategory: Record<string, number> = {}
  for (const p of allPlacements) {
    byType[p.type] = (byType[p.type] ?? 0) + 1
    byCategory[p.category] = (byCategory[p.category] ?? 0) + 1
  }

  const updatedScene: Scene = {
    ...scene,
    nodes,
    updatedAt: new Date().toISOString(),
    metadata: {
      ...scene.metadata,
      nodeCount: nodes.length,
      lightingApplied: true,
      lightCount: allPlacements.length,
    },
  }

  return {
    scene: updatedScene,
    result: {
      placements: allPlacements,
      nodesAdded,
      errors: validation.errors,
      warnings: validation.warnings,
      stats: {
        totalLights: allPlacements.length,
        byType,
        byCategory,
        blueprintLights: blueprintPlacements.length,
        autoGenerated: autoPlacements.length,
      },
    },
  }
}
