import type { LightDefinition, Vec3, BoothDimensions } from '@/types/blueprint'
import type { LightPlacement, EngineLightType } from './lighting-types'
import { temperatureToHex } from './light-presets'

function mapBlueprintType(bpType: string): EngineLightType {
  switch (bpType.toLowerCase()) {
    case 'spotlight': return 'spot'
    case 'led_strip': return 'led_strip'
    case 'backlit_panel': return 'area'
    case 'ambient': return 'sun'
    case 'neon': return 'led_strip'
    case 'projection': return 'spot'
    case 'point': return 'point'
    case 'directional': return 'sun'
    case 'area': return 'area'
    default: return 'point'
  }
}

function categoryFromType(type: EngineLightType, bpType: string): 'ambient' | 'key' | 'fill' | 'accent' | 'task' | 'decorative' {
  if (bpType === 'ambient' || bpType === 'directional') return 'ambient'
  if (bpType === 'neon' || bpType === 'led_strip') return 'decorative'
  if (bpType === 'backlit_panel') return 'fill'
  if (type === 'spot') return 'accent'
  if (type === 'area') return 'key'
  return 'task'
}

function defaultIntensity(type: EngineLightType): number {
  switch (type) {
    case 'sun': return 50
    case 'area': return 400
    case 'spot': return 600
    case 'point': return 200
    case 'led_strip': return 150
  }
}

export function resolveBlueprintLight(light: LightDefinition, index: number): LightPlacement {
  const type = mapBlueprintType(light.type)
  const category = categoryFromType(type, light.type)
  const temperature = (light.metadata?.temperature as number) ?? 4000
  const color = light.color || temperatureToHex(temperature)

  return {
    lightId: light.id ?? `bp_light_${index}`,
    type,
    category,
    position: light.position ?? { x: 0, y: 0, z: 0 },
    rotation: light.rotation ?? { x: 0, y: 0, z: 0 },
    target: light.target ?? null,
    color,
    temperature,
    intensity: light.intensity ?? defaultIntensity(type),
    castShadow: light.castShadow ?? (type === 'spot'),
    angle: light.angle ?? (type === 'spot' ? 45 : 0),
    decay: light.decay ?? 2,
    areaWidth: (light.metadata?.width as number) ?? (type === 'area' ? 2 : type === 'led_strip' ? 3 : 1),
    areaHeight: (light.metadata?.height as number) ?? (type === 'area' ? 2 : type === 'led_strip' ? 0.05 : 1),
    spotBlend: (light.metadata?.spotBlend as number) ?? 0.15,
    visible: true,
    metadata: {
      lightId: light.id,
      sourceLightType: light.type,
      ...light.metadata,
    },
  }
}

export function generateAutoLights(dims: BoothDimensions, existingPlacements: LightPlacement[]): LightPlacement[] {
  const auto: LightPlacement[] = []
  const hasAmbient = existingPlacements.some(p => p.category === 'ambient')
  const hasKey = existingPlacements.some(p => p.category === 'key')

  if (!hasAmbient) {
    auto.push({
      lightId: 'auto_ambient',
      type: 'sun',
      category: 'ambient',
      position: { x: 0, y: dims.height + 2, z: 0 },
      rotation: { x: -45, y: 30, z: 0 },
      target: null,
      color: temperatureToHex(5500),
      temperature: 5500,
      intensity: 30,
      castShadow: false,
      angle: 0,
      decay: 0,
      areaWidth: 1,
      areaHeight: 1,
      spotBlend: 0,
      visible: true,
      metadata: { autoGenerated: true, purpose: 'ambient_fill' },
    })
  }

  if (!hasKey) {
    const cx = 0
    const cz = 0
    auto.push({
      lightId: 'auto_key',
      type: 'area',
      category: 'key',
      position: { x: cx, y: dims.height - 0.1, z: cz },
      rotation: { x: 0, y: 0, z: 0 },
      target: null,
      color: temperatureToHex(4000),
      temperature: 4000,
      intensity: 500,
      castShadow: true,
      angle: 0,
      decay: 2,
      areaWidth: Math.min(dims.width * 0.6, 4),
      areaHeight: Math.min(dims.depth * 0.4, 3),
      spotBlend: 0,
      visible: true,
      metadata: { autoGenerated: true, purpose: 'overhead_key' },
    })
  }

  return auto
}
